# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision/GuiMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class GuiMsg(genpy.Message):
  _md5sum = "e90f192dd27b89705a548c0e1f4f2691"
  _type = "vision/GuiMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
uint8 button
uint8 machine
uint8 m_state
uint8 t_course
"""
  __slots__ = ['stamp','button','machine','m_state','t_course']
  _slot_types = ['time','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,button,machine,m_state,t_course

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GuiMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.button is None:
        self.button = 0
      if self.machine is None:
        self.machine = 0
      if self.m_state is None:
        self.m_state = 0
      if self.t_course is None:
        self.t_course = 0
    else:
      self.stamp = genpy.Time()
      self.button = 0
      self.machine = 0
      self.m_state = 0
      self.t_course = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I4B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.button, _x.machine, _x.m_state, _x.t_course))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.stamp.secs, _x.stamp.nsecs, _x.button, _x.machine, _x.m_state, _x.t_course,) = _get_struct_2I4B().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I4B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.button, _x.machine, _x.m_state, _x.t_course))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.stamp.secs, _x.stamp.nsecs, _x.button, _x.machine, _x.m_state, _x.t_course,) = _get_struct_2I4B().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4B = None
def _get_struct_2I4B():
    global _struct_2I4B
    if _struct_2I4B is None:
        _struct_2I4B = struct.Struct("<2I4B")
    return _struct_2I4B
